@startuml

partition "**Working Source (Simple Flow)**"{
start

: Include gas sensor MiCS-4514 library;
: Include oxygen sensor library;
: Set a calibration time of 3 minutes for MiCS-4514 sensor;

repeat
if (is both the Sensor connected successfully?) then (yes)
    : Read the oxygen data from oxygen snsor;
    : Display the data in Volume percentage;
    if (is MicS-4514 Sensor in Wake Up Mode?) then (yes)
        : Read the required gas data from the sensor in a interval;
        : Display the data in PPM (Parts Per Million) unit;
    else (No)
        :Display an alert message regarding Sensor Mode;
    endif
else (No)
    : Display an alert message regarding connectivity;

endif

repeat while
}

@enduml